### PR TITLE
Add domain to typeclass auth example

### PR DESCRIPTION
**Pull request by wsargent**

### CODE REVIEW

**Comment by wsargent** [comment]
Possibly of interest to @SethTisue

**Comment by wsargent** [comment]
crud, no write access :-(

**Comment by wsargent** [comment]
@SethTisue I'd like to turn the README into a blog post on tersesystems.com if that's okay

**Comment by wsargent** [comment]
Okay, I'm going to turn it into a scaladays talk instead :-)

**Comment by SethTisue** [comment]
I've added you as an outside collaborator to the repo, so you should be able (perhaps after accepting an invite?) to merge the PR yourself now.

**Pull request closed without merging**
